# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    med.serv:
        class: AppBundle\Services\MedService
    med_listener1:
        class: AppBundle\EventListener\TestLendSubcriber
        arguments: ["@med.serv"]
        tags:
            - { name: kernel.event_subscriber}
#    med_listener2:
#        class: AppBundle\EventListener\TestLendListener
#        arguments: ["@med.serv"]
#        tags:
#            - { name: kernel.event_listener, event: med.lend, method: lendol}
#    med_listener:
#        class: AppBundle\EventListener\TestListener
#        tags:
#            - { name: kernel.event_listener, event: kernel.response, method: lendol}
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
